### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by yosuaalvin** [jerrykal/AI_CUP_2023_Spring_Computer_Vision#1]
do you have an example dataset?

**Comment by jerrykal** [comment]
Sorry, I personally didn't kept the dataset after the competition ended. And I wasn't sure if they even make the data public at the first place.

Maybe you can ask the competition topic provider for the dataset.

here's the website of the competition: https://aidea-web.tw/topic/cbea66cc-a993-4be8-933d-1aa9779001f8

**Comment by yosuaalvin** [comment]
when i try why the backhand result is show all 1? is there is a problem in backhand recognition?
